
const Store = {
 get(key, fallback){try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch(e){return fallback}},
 set(key,val){localStorage.setItem(key,JSON.stringify(val))},
 cart(){return this.get("nova_cart",[])},
 wishlist(){return this.get("nova_wishlist",[])},
 user(){return this.get("nova_user",null)},
 orders(){return this.get("nova_orders",[])},
 coupon(){return this.get("nova_coupon",null)}
};
const money = n => `₹${Number(n).toLocaleString("en-IN")}`;
function toast(message,type="success"){const wrap=document.querySelector(".toast-wrap")||(()=>{const w=document.createElement("div");w.className="toast-wrap";document.body.appendChild(w);return w})();const el=document.createElement("div");el.className=`toast ${type}`;el.textContent=message;wrap.appendChild(el);setTimeout(()=>el.remove(),2800)}
function getProduct(id){return PRODUCTS.find(p=>p.id===Number(id))}
function cartCount(){return Store.cart().reduce((s,i)=>s+i.qty,0)}
function wishCount(){return Store.wishlist().length}
function updateCounters(){document.querySelectorAll("[data-cart-count]").forEach(e=>e.textContent=cartCount());document.querySelectorAll("[data-wish-count]").forEach(e=>e.textContent=wishCount())}
function isWished(id){return Store.wishlist().includes(Number(id))}
function toggleWishlist(id){id=Number(id);let list=Store.wishlist();if(list.includes(id)){list=list.filter(x=>x!==id);toast("Removed from wishlist","success")}else{list.push(id);toast("Added to wishlist","success")}Store.set("nova_wishlist",list);updateCounters();renderWishlistButtons()}
function renderWishlistButtons(){document.querySelectorAll("[data-wish]").forEach(btn=>{const id=Number(btn.dataset.wish);btn.classList.toggle("active",isWished(id));btn.innerHTML=isWished(id)?"<i class='fa-solid fa-heart'></i>":"<i class='fa-regular fa-heart'></i>";btn.setAttribute("aria-label",isWished(id)?"Remove from wishlist":"Add to wishlist")})}
function addToCart(id,qty=1,size=null,color=null){id=Number(id);const p=getProduct(id);if(!p)return;let cart=Store.cart();const key=`${id}-${size||p.sizes[0]}-${color||p.colors[0]}`;const found=cart.find(i=>i.key===key);if(found)found.qty+=Number(qty);else cart.push({key,id,qty:Number(qty),size:size||p.sizes[0],color:color||p.colors[0]});Store.set("nova_cart",cart);updateCounters();toast(`${p.name} added to cart`)}
function cartDetails(){return Store.cart().map(i=>({...i,p:getProduct(i.id)})).filter(i=>i.p)}
function subtotal(){return cartDetails().reduce((s,i)=>s+i.p.price*i.qty,0)}
function discountAmount(){const c=Store.coupon();if(!c)return 0;return Math.round(subtotal()*c.rate)}
function shipping(){const sub=subtotal()-discountAmount();return sub===0?0:sub>=2500?0:99}
function grandTotal(){return subtotal()-discountAmount()+shipping()}
function setCoupon(code){code=code.trim().toUpperCase();const coupons={WELCOME10:.10,SAVE20:.20,FASHION15:.15};if(!code){Store.set("nova_coupon",null);toast("Coupon cleared");return true}if(!coupons[code]){toast("Invalid demo coupon","error");return false}if(Store.coupon()){toast("A coupon is already applied","error");return false}Store.set("nova_coupon",{code,rate:coupons[code]});toast(`${code} applied successfully`);return true}
function productCard(p){return `<article class="product-card reveal"><div class="product-media"><a href="product.html?id=${p.id}" aria-label="View ${p.name}"><img src="${p.image}" alt="${p.name}" loading="lazy"></a><span class="product-badge">${p.badge}</span><div class="product-wish"><button data-wish="${p.id}" class="${isWished(p.id)?"active":""}" aria-label="${isWished(p.id)?"Remove from":"Add to"} wishlist">${isWished(p.id)?"<i class='fa-solid fa-heart'></i>":"<i class='fa-regular fa-heart'></i>"}</button></div></div><div class="product-info"><div class="product-cat">${p.category} · ${p.subCategory}</div><div class="product-name">${p.name}</div><div class="rating">${"★".repeat(Math.round(p.rating))}<span>${p.rating} (${p.reviews})</span></div><div class="price-row"><span class="price">${money(p.price)}</span><span class="old-price">${money(p.originalPrice)}</span><span class="discount">${Math.round((1-p.price/p.originalPrice)*100)}% OFF</span></div><div class="card-actions"><a class="btn btn-ghost" href="product.html?id=${p.id}">Details</a><button class="btn btn-primary" data-add="${p.id}"><i class="fa-solid fa-bag-shopping"></i> Add</button></div></div></article>`}
function renderGrid(container,items){container.innerHTML=items.length?items.map(productCard).join(""):`<div class="empty" style="grid-column:1/-1"><i class="fa-solid fa-magnifying-glass"></i><h2>No pieces found</h2><p>Try another search or clear your filters.</p><button class="btn btn-primary" onclick="location.reload()">Reset view</button></div>`;bindProductActions(container)}
function bindProductActions(root=document){root.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addToCart(b.dataset.add));root.querySelectorAll("[data-wish]").forEach(b=>b.onclick=()=>toggleWishlist(b.dataset.wish))}
function initHeader(){document.querySelectorAll("[data-menu]").forEach(b=>b.onclick=()=>document.querySelector(".nav")?.classList.toggle("open"));document.querySelectorAll(".search-box").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();const q=form.querySelector("input").value.trim();location.href=q?`shop.html?search=${encodeURIComponent(q)}`:"shop.html"}));updateCounters();renderWishlistButtons();const user=Store.user();document.querySelectorAll("[data-account]").forEach(a=>a.textContent=user?`Hi, ${user.name.split(" ")[0]}`:"Account")}
function footer(){return `<footer class="footer"><div class="container"><div class="footer-grid"><div><a class="logo" href="index.html"><span class="logo-mark">N</span><span>NOVA / WEAR<small>MODERN CLOTHING CO.</small></span></a><p style="max-width:360px;margin-top:18px">A dark, modern fashion storefront built from the original college project and upgraded into a functional Vanilla JavaScript e-commerce demo.</p></div><div><h3>Explore</h3><ul><li><a href="shop.html">Shop all</a></li><li><a href="shop.html?category=Men">Men</a></li><li><a href="shop.html?category=Women">Women</a></li><li><a href="shop.html?category=Kids">Kids</a></li></ul></div><div><h3>Account</h3><ul><li><a href="wishlist.html">Wishlist</a></li><li><a href="cart.html">Cart</a></li><li><a href="orders.html">My orders</a></li><li><a href="login.html">Login</a></li></ul></div><div><h3>Help</h3><ul><li><a href="about.html">About us</a></li><li><a href="contact.html">Contact</a></li><li><a href="checkout.html">Checkout</a></li></ul></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Nova / Wear. Demo project.</span><span>HTML · CSS · Vanilla JavaScript · localStorage</span></div></div></footer>`}
function initFooter(){const f=document.querySelector("[data-footer]");if(f)f.innerHTML=footer()}
function setupGlobal(){initHeader();initFooter();document.addEventListener("click",e=>{const link=e.target.closest("[data-cat]");if(link){e.preventDefault();location.href=`shop.html?category=${encodeURIComponent(link.dataset.cat)}`}})}
document.addEventListener("DOMContentLoaded",setupGlobal);
