
const PRODUCTS = [
 {id:1,name:"Noir Tailored Jacket",category:"Men",subCategory:"Jackets",price:2499,originalPrice:3499,rating:4.8,reviews:126,image:"cat-1.jpg",additionalImages:["product-3.jpg","offer-1.png"],sizes:["S","M","L","XL"],colors:["Black","Midnight Blue"],description:"A clean structured jacket with a sharp silhouette, soft inner feel and understated hardware for elevated everyday dressing.",badge:"BESTSELLER",popularity:98,newest:8},
 {id:2,name:"Ivory Off-Shoulder Knit",category:"Women",subCategory:"Tops",price:1799,originalPrice:2499,rating:4.7,reviews:94,image:"cat-2.jpg",additionalImages:["offer-2.png"],sizes:["XS","S","M","L"],colors:["Ivory","Stone"],description:"Soft-touch knitwear with an elegant off-shoulder neckline designed for relaxed premium styling.",badge:"TRENDING",popularity:95,newest:9},
 {id:3,name:"Junior Denim Layer",category:"Kids",subCategory:"Jackets",price:1399,originalPrice:1899,rating:4.6,reviews:72,image:"cat-3.jpg",additionalImages:["product-2.jpg"],sizes:["3-4Y","5-6Y","7-8Y","9-10Y"],colors:["Denim Blue"],description:"A playful denim layer built for movement, weekend outings and effortless everyday looks.",badge:"NEW",popularity:91,newest:10},
 {id:4,name:"Luna Mini Dress",category:"Women",subCategory:"Dresses",price:2299,originalPrice:2999,rating:4.9,reviews:211,image:"product-1.jpg",additionalImages:["offer-2.png"],sizes:["XS","S","M","L","XL"],colors:["Pearl","Black"],description:"A minimal mini dress with a clean line and versatile shape that moves easily from day plans to evening edits.",badge:"EDITOR'S PICK",popularity:99,newest:7},
 {id:5,name:"Midnight Street Jacket",category:"Men",subCategory:"Jackets",price:2699,originalPrice:3799,rating:4.8,reviews:164,image:"product-3.jpg",additionalImages:["cat-1.jpg"],sizes:["S","M","L","XL","XXL"],colors:["Black"],description:"A street-ready layer combining a classic leather-inspired profile with an easy modern fit.",badge:"BESTSELLER",popularity:97,newest:6},
 {id:6,name:"Sculpt Rib Dress",category:"Women",subCategory:"Dresses",price:1999,originalPrice:2799,rating:4.7,reviews:118,image:"product-4.jpg",additionalImages:["offer-1.png"],sizes:["XS","S","M","L"],colors:["Black","Espresso"],description:"A figure-skimming rib dress made for clean silhouettes and minimal styling.",badge:"TRENDING",popularity:94,newest:5},
 {id:7,name:"Classic Essential Tee",category:"Men",subCategory:"T-Shirts",price:799,originalPrice:1199,rating:4.5,reviews:340,image:"product-3.jpg",additionalImages:["cat-1.jpg"],sizes:["S","M","L","XL","XXL"],colors:["Black","Blue","White"],description:"A dependable everyday tee with a comfortable fit and understated premium finish.",badge:"VALUE PICK",popularity:100,newest:4},
 {id:8,name:"Soft Lounge Layer",category:"Women",subCategory:"Tops",price:1199,originalPrice:1699,rating:4.6,reviews:87,image:"offer-2.png",additionalImages:["cat-2.jpg"],sizes:["S","M","L","XL"],colors:["White","Stone"],description:"A soft, versatile top designed for layering and easy off-duty outfits.",badge:"NEW",popularity:89,newest:10}
];
window.PRODUCTS = PRODUCTS;
