
document.addEventListener("DOMContentLoaded",()=>{
 const id=new URLSearchParams(location.search).get("id")||1,p=getProduct(id);const root=document.querySelector("#product-root");if(!p||!root)return;
 let selectedSize=p.sizes[Math.min(1,p.sizes.length-1)],selectedColor=p.colors[0],qty=1;
 const gallery=[p.image,...p.additionalImages];
 root.innerHTML=`<div class="product-detail"><div><div class="gallery-main"><img id="main-product-img" src="${gallery[0]}" alt="${p.name}"></div><div class="thumbs">${gallery.map((x,i)=>`<button class="thumb ${i===0?"active":""}" data-img="${x}"><img src="${x}" alt="${p.name} view ${i+1}"></button>`).join("")}</div></div><div class="detail-copy"><div class="product-cat">${p.category} · ${p.subCategory}</div><h1>${p.name}</h1><div class="detail-meta"><span class="rating">${"★".repeat(Math.round(p.rating))}</span><span class="muted">${p.rating} · ${p.reviews} reviews</span></div><div><span class="detail-price">${money(p.price)}</span> <span class="old-price">${money(p.originalPrice)}</span> <span class="discount">${Math.round((1-p.price/p.originalPrice)*100)}% OFF</span></div><p class="detail-desc">${p.description}</p><div class="option-label">Select size</div><div class="option-row">${p.sizes.map(s=>`<button class="option ${s===selectedSize?"selected":""}" data-size="${s}">${s}</button>`).join("")}</div><div class="option-label">Select colour</div><div class="option-row">${p.colors.map(c=>`<button class="option ${c===selectedColor?"selected":""}" data-color="${c}">${c}</button>`).join("")}</div><div class="option-label">Quantity</div><div class="qty"><button id="minus" aria-label="Decrease quantity">−</button><input id="qty" value="1" inputmode="numeric" aria-label="Quantity"><button id="plus" aria-label="Increase quantity">+</button></div><div class="detail-actions"><button class="btn btn-primary" id="add-detail"><i class="fa-solid fa-bag-shopping"></i> Add to cart</button><button class="btn" id="buy-detail">Buy now</button><button class="icon-btn" id="wish-detail" data-wish="${p.id}" aria-label="Wishlist"><i class="fa-${isWished(p.id)?"solid":"regular"} fa-heart"></i></button></div><div class="info-box"><div class="mini-info"><i class="fa-solid fa-truck"></i> Free shipping over ₹2,500</div><div class="mini-info"><i class="fa-solid fa-rotate-left"></i> 14-day return window</div><div class="mini-info"><i class="fa-solid fa-shield"></i> Demo secure checkout</div></div></div></div>`;
 root.querySelectorAll("[data-img]").forEach(b=>b.onclick=()=>{document.querySelector("#main-product-img").src=b.dataset.img;root.querySelectorAll(".thumb").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
 root.querySelectorAll("[data-size]").forEach(b=>b.onclick=()=>{selectedSize=b.dataset.size;root.querySelectorAll("[data-size]").forEach(x=>x.classList.toggle("selected",x===b))});
 root.querySelectorAll("[data-color]").forEach(b=>b.onclick=()=>{selectedColor=b.dataset.color;root.querySelectorAll("[data-color]").forEach(x=>x.classList.toggle("selected",x===b))});
 const input=root.querySelector("#qty");const sync=()=>{qty=Math.max(1,Math.min(20,Number(input.value)||1));input.value=qty};root.querySelector("#minus").onclick=()=>{qty--;sync()};root.querySelector("#plus").onclick=()=>{qty++;sync()};input.onchange=sync;
 root.querySelector("#add-detail").onclick=()=>addToCart(p.id,qty,selectedSize,selectedColor);root.querySelector("#buy-detail").onclick=()=>{addToCart(p.id,qty,selectedSize,selectedColor);location.href="checkout.html"};root.querySelector("#wish-detail").onclick=()=>toggleWishlist(p.id);
 const rel=PRODUCTS.filter(x=>x.id!==p.id).slice(0,4);document.querySelector("#related-grid").innerHTML=rel.map(productCard).join("");bindProductActions(document.querySelector("#related-grid"));
});
